name: CI/CD
run-name: ${{ github.actor }} CI/CD
on: [push]

jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [v20.11.0]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build
      - name: lint code
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to server and run script
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "sh ${{ secrets.PATH_TO_SCRIPT }}"
